name: TURF_TOWN_
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0' # Good practice to use a version range

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  objectbox: ^5.0.1
  google_fonts: ^6.3.2
  provider: ^6.1.5+1

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

dev_dependencies:
  objectbox_generator: ^5.0.1
  build_runner: ^2.10.1
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints
  flutter_lints: ^5.0.0

# ---

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/ # Declares all files within the 'assets/images/' directory.