import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Group7314(),
        ]),
      ),
    );
  }
}

class Group7314 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 800,
          child: Stack(
            children: [
              Positioned(
                left: 315.80,
                top: 24.99,
                child: Container(
                  width: 34.85,
                  height: 34.85,
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 268.69,
                top: 24.99,
                child: Container(
                  width: 34.85,
                  height: 34.85,
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 10.91,
                top: 11,
                child: SizedBox(
                  width: 220.16,
                  height: 49,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: 'Cricket ',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 40,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                        TextSpan(
                          text: 'Scorer',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 20,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 203.43,
                top: 552,
                child: Container(
                  width: 42.46,
                  height: 44,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF19005D),
                    shape: OvalBorder(),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 10,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 222.41,
                top: 565.73,
                child: SizedBox(
                  width: 26.89,
                  height: 27.87,
                  child: Text(
                    '6\n',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 9,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 152.58,
                top: 552,
                child: Container(
                  width: 42.46,
                  height: 44,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF19005D),
                    shape: OvalBorder(),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 10,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 171.56,
                top: 565.73,
                child: SizedBox(
                  width: 26.89,
                  height: 27.87,
                  child: Text(
                    '5\n',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 9,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 102.71,
                top: 552,
                child: Container(
                  width: 42.46,
                  height: 44,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF19005D),
                    shape: OvalBorder(),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 10,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 120.70,
                top: 565.73,
                child: SizedBox(
                  width: 26.89,
                  height: 27.87,
                  child: Text(
                    '4\n',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 9,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 201.44,
                top: 501,
                child: Container(
                  width: 43.88,
                  height: 44,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF19005D),
                    shape: OvalBorder(),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 10,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 221.10,
                top: 514.56,
                child: SizedBox(
                  width: 27.07,
                  height: 25.21,
                  child: Text(
                    '3\n',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 9,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 151.58,
                top: 501,
                child: Container(
                  width: 42.46,
                  height: 44,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF19005D),
                    shape: OvalBorder(),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 10,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 170.56,
                top: 514.73,
                child: SizedBox(
                  width: 26.89,
                  height: 27.87,
                  child: Text(
                    '2\n',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 9,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 102.71,
                top: 501,
                child: Container(
                  width: 41.14,
                  height: 44,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF19005D),
                    shape: OvalBorder(),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 10,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 121.54,
                top: 515.73,
                child: SizedBox(
                  width: 26.05,
                  height: 27.87,
                  child: Text(
                    '1\n',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 9,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 152.58,
                top: 603,
                child: Container(
                  width: 41.14,
                  height: 44,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF1D006D),
                    shape: OvalBorder(),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 10,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 171.40,
                top: 616.73,
                child: SizedBox(
                  width: 26.05,
                  height: 27.87,
                  child: Text(
                    '0\n',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 9,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 102.71,
                top: 107,
                child: SizedBox(
                  width: 209.02,
                  height: 27.59,
                  child: Text(
                    'Score Board',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 24,
                      fontFamily: 'Open Sans',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 229.36,
                top: 435,
                child: Container(
                  width: 29.92,
                  height: 29.50,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF02500A),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 186.48,
                top: 435,
                child: Container(
                  width: 29.92,
                  height: 29.50,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFAC0000),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 143.60,
                top: 435.98,
                child: Container(
                  width: 29.92,
                  height: 29.50,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFD9D9D9),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 100.72,
                top: 435,
                child: Container(
                  width: 29.92,
                  height: 29.50,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF02510A),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 271.25,
                top: 435,
                child: Container(
                  width: 29.92,
                  height: 29.50,
                  decoration: ShapeDecoration(
                    color: const Color(0xCCD9D9D9),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 57.84,
                top: 435,
                child: Container(
                  width: 29.92,
                  height: 29.50,
                  decoration: ShapeDecoration(
                    color: const Color(0xCCD9D9D9),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 69.80,
                top: 438.15,
                child: SizedBox(
                  width: 24.54,
                  height: 22.68,
                  child: Text(
                    '1',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 110.05,
                top: 437.19,
                child: SizedBox(
                  width: 24.54,
                  height: 22.68,
                  child: Text(
                    '4',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 153.67,
                top: 439.14,
                child: SizedBox(
                  width: 24.54,
                  height: 22.68,
                  child: Text(
                    '0',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 194.26,
                top: 438.18,
                child: SizedBox(
                  width: 24.54,
                  height: 22.68,
                  child: Text(
                    'W',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 222.38,
                top: 423,
                child: SizedBox(
                  width: 36.90,
                  height: 31,
                  child: Text(
                    '6',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 145.60,
                top: 413,
                child: SizedBox(
                  width: 74.79,
                  height: 18,
                  child: Text(
                    'This Over',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 357.02,
                  height: 800,
                  decoration: BoxDecoration(color: const Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 357.02,
                  height: 800,
                  decoration: BoxDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.50, -0.00),
                      end: Alignment(0.50, 1.00),
                      colors: [const Color(0xFF140088), Colors.black],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 306.13,
                top: 21.02,
                child: Opacity(
                  opacity: 0.90,
                  child: Container(
                    width: 24.97,
                    height: 24.97,
                    child: Stack(),
                  ),
                ),
              ),
              Positioned(
                left: 267.69,
                top: 27.99,
                child: Container(
                  width: 34.85,
                  height: 34.85,
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 12.91,
                top: 3,
                child: SizedBox(
                  width: 220.16,
                  height: 49,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: 'Cricket ',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 40,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                        TextSpan(
                          text: 'Scorer',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 20,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 314.15,
                top: 633.52,
                child: SizedBox(
                  width: 27.37,
                  height: 50.51,
                  child: Text(
                    '6\n',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 15,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 265.85,
                top: 608.74,
                child: SizedBox(
                  width: 27.37,
                  height: 50.51,
                  child: Text(
                    '5\n',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 15,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 31.19,
                top: 635.90,
                child: SizedBox(
                  width: 31.10,
                  height: 35.57,
                  child: Text(
                    '4\n',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 15,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 79.68,
                top: 614.34,
                child: SizedBox(
                  width: 31.30,
                  height: 32.18,
                  child: Text(
                    '3\n',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 15,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 217.81,
                top: 593.17,
                child: SizedBox(
                  width: 31.10,
                  height: 35.57,
                  child: Text(
                    '2\n',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 15,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 169.60,
                top: 578.93,
                child: SizedBox(
                  width: 35.83,
                  height: 40.17,
                  child: Text(
                    '0\n',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 15,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 124.58,
                top: 590.87,
                child: SizedBox(
                  width: 34.14,
                  height: 40.17,
                  child: Text(
                    '1\n',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 15,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 15,
                top: 734,
                child: Container(
                  width: 55,
                  height: 55,
                  decoration: ShapeDecoration(
                    color: const Color(0x7F00C4FF),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 27,
                top: 751,
                child: SizedBox(
                  width: 67,
                  child: Text(
                    'Extras',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 11,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 170,
                top: 764,
                child: Container(width: 11, height: 12, child: Stack()),
              ),
              Positioned(
                left: 121.66,
                top: 97,
                child: SizedBox(
                  width: 209.02,
                  height: 27.59,
                  child: Text(
                    'Score Board',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Open Sans',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 43.88,
                top: 487,
                child: Container(
                  width: 270.25,
                  height: 45,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.50, 0.00),
                      end: Alignment(0.50, 0.97),
                      colors: [const Color(0xFF2F363F), const Color(0xFF1C2026)],
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 229.36,
                top: 493,
                child: Container(
                  width: 29.92,
                  height: 29.50,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF02500A),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 186.48,
                top: 493,
                child: Container(
                  width: 29.92,
                  height: 29.50,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFAC0000),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 143.60,
                top: 493.98,
                child: Container(
                  width: 29.92,
                  height: 29.50,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFD9D9D9),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 100.72,
                top: 493,
                child: Container(
                  width: 29.92,
                  height: 29.50,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF02510A),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 271.25,
                top: 493,
                child: Container(
                  width: 29.92,
                  height: 29.50,
                  decoration: ShapeDecoration(
                    color: const Color(0xCCD9D9D9),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 57.84,
                top: 493,
                child: Container(
                  width: 29.92,
                  height: 29.50,
                  decoration: ShapeDecoration(
                    color: const Color(0xCCD9D9D9),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 69.80,
                top: 496.15,
                child: SizedBox(
                  width: 24.54,
                  height: 22.68,
                  child: Text(
                    '1',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 110.05,
                top: 495.19,
                child: SizedBox(
                  width: 24.54,
                  height: 22.68,
                  child: Text(
                    '4',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 153.67,
                top: 497.14,
                child: SizedBox(
                  width: 24.54,
                  height: 22.68,
                  child: Text(
                    '0',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 194.26,
                top: 496.18,
                child: SizedBox(
                  width: 24.54,
                  height: 22.68,
                  child: Text(
                    'W',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 238.86,
                top: 496.23,
                child: SizedBox(
                  width: 24.54,
                  height: 22.68,
                  child: Text(
                    '6',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 145.60,
                top: 471,
                child: SizedBox(
                  width: 74.79,
                  height: 18,
                  child: Text(
                    'This Over',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 45.87,
                top: 187,
                child: SizedBox(
                  width: 97.73,
                  height: 25,
                  child: Text(
                    'CRR : 300.00',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 15,
                      fontFamily: 'Open Sans',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 44.88,
                top: 203,
                child: SizedBox(
                  width: 97.73,
                  height: 25,
                  child: Text(
                    'NRR : 7.09',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 15,
                      fontFamily: 'Open Sans',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 262.27,
                top: 197.60,
                child: SizedBox(
                  width: 62.90,
                  height: 35.98,
                  child: Text(
                    '(7.3)',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 15,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 239.34,
                top: 158,
                child: SizedBox(
                  width: 102.71,
                  height: 63.43,
                  child: Text(
                    '30-0',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 35,
                      fontFamily: 'Open Sans',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 63.82,
                top: 155,
                child: SizedBox(
                  width: 93.74,
                  height: 34,
                  child: Text(
                    'IND',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 25,
                      fontFamily: 'Open Sans',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 268.24,
                top: 21.02,
                child: Opacity(
                  opacity: 0.90,
                  child: Container(
                    width: 24.97,
                    height: 24.97,
                    child: Stack(),
                  ),
                ),
              ),
              Positioned(
                left: 11,
                top: 253,
                child: Container(
                  width: 335,
                  height: 116,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF1C2026),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 11,
                top: 253,
                child: Container(
                  width: 335,
                  height: 116,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF1C2026),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 11,
                top: 253,
                child: Container(
                  width: 335,
                  height: 36,
                  decoration: BoxDecoration(
                    color: const Color(0xFF2E353E),
                    border: Border.all(width: 1),
                  ),
                ),
              ),
              Positioned(
                left: 26,
                top: 305,
                child: Opacity(
                  opacity: 0.70,
                  child: Text(
                    'Virat kholi',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 26,
                top: 333,
                child: Text(
                  'MS Dhoni*',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 159,
                top: 305,
                child: Text(
                  '4',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFFAAAAAA),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 158,
                top: 261,
                child: Text(
                  'R',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 158,
                top: 333,
                child: Text(
                  '6',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFFAAAAAA),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 195,
                top: 305,
                child: Text(
                  '13',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFFAAAAAA),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 196,
                top: 261,
                child: Text(
                  'B',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 198,
                top: 333,
                child: Text(
                  '1',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFFAAAAAA),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 235,
                top: 305,
                child: Text(
                  '0',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFFAAAAAA),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 230,
                top: 261,
                child: Text(
                  '4s',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 234,
                top: 333,
                child: Text(
                  '0',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFFAAAAAA),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 273,
                top: 305,
                child: Text(
                  '0',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFFAAAAAA),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 268,
                top: 261,
                child: Text(
                  '6s',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 274,
                top: 333,
                child: Text(
                  '1',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFFAAAAAA),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 302,
                top: 305,
                child: Text(
                  '30.0',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFFAAAAAA),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 305,
                top: 261,
                child: Text(
                  'SR',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 297,
                top: 333,
                child: Text(
                  '600.0',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFFAAAAAA),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 26,
                top: 261,
                child: Text(
                  'Batsman',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 13,
                top: 375,
                child: Container(
                  width: 332,
                  height: 88,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF1C2026),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 13,
                top: 375,
                child: Container(
                  width: 332,
                  height: 88,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF1C2026),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 13,
                top: 375,
                child: Container(
                  width: 332,
                  height: 37.71,
                  decoration: BoxDecoration(
                    color: const Color(0xFF2E353E),
                    border: Border.all(width: 1),
                  ),
                ),
              ),
              Positioned(
                left: 27.87,
                top: 429.48,
                child: SizedBox(
                  width: 97.12,
                  height: 18.86,
                  child: Text(
                    'Starc',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 197.33,
                top: 429.48,
                child: SizedBox(
                  width: 7.93,
                  height: 18.86,
                  child: Text(
                    '7',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFFAAAAAA),
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 195.35,
                top: 383.38,
                child: SizedBox(
                  width: 10.90,
                  height: 22,
                  child: Text(
                    'O',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 14,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 229,
                top: 429,
                child: SizedBox(
                  width: 23,
                  height: 19,
                  child: Text(
                    '13',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFFAAAAAA),
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 234,
                top: 383.38,
                child: SizedBox(
                  width: 8.92,
                  height: 22,
                  child: Text(
                    'R',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 14,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 272.65,
                top: 429.48,
                child: SizedBox(
                  width: 7.93,
                  height: 18.86,
                  child: Text(
                    '1',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFFAAAAAA),
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 268.69,
                top: 383.38,
                child: SizedBox(
                  width: 13.87,
                  height: 22,
                  child: Text(
                    'W',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 14,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 305.36,
                top: 429.48,
                child: SizedBox(
                  width: 18.83,
                  height: 18.86,
                  child: Text(
                    '0.0',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFFAAAAAA),
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 305.36,
                top: 383.38,
                child: SizedBox(
                  width: 16.85,
                  height: 22,
                  child: Text(
                    'ER',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 14,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 27.87,
                top: 383.38,
                child: SizedBox(
                  width: 47.57,
                  height: 22,
                  child: Text(
                    'Bowler',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 14,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 206,
                top: 622,
                child: Container(
                  width: 39,
                  height: 75,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 287,
                top: 734,
                child: Container(
                  width: 55,
                  height: 55,
                  decoration: ShapeDecoration(
                    color: const Color(0x7F00C4FF),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 304,
                top: 741,
                child: Container(
                  width: 21.50,
                  height: 21.50,
                  decoration: ShapeDecoration(
                    color: const Color(0x0500C4FF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(50),
                    ),
                  ),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 301,
                top: 762,
                child: SizedBox(
                  width: 33,
                  height: 16,
                  child: Text(
                    'Undo',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 11,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 148,
                top: 663,
                child: Container(
                  width: 55,
                  height: 55,
                  decoration: ShapeDecoration(
                    color: const Color(0x7F00C4FF),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 156,
                top: 683,
                child: SizedBox(
                  width: 43,
                  height: 20,
                  child: Text(
                    'Wicket\n',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 11,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 136,
                top: 743,
                child: SizedBox(
                  width: 87,
                  height: 19,
                  child: Text(
                    ' Swap Player',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}